[33mWARNING [0m test_integration:test_integration.py:107 Error when accessing Grafana dashboard: HTTPConnectionPool(host='grafana-0.grafana-endpoints.cos-lite.svc.cluster.local', port=3000): Max retries exceeded with url: /api/search?query=5G%20Network%20Overview (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x719b8eb782b0>: Failed to resolve 'grafana-0.grafana-endpoints.cos-lite.svc.cluster.local' ([Errno -3] Temporary failure in name resolution)")). Retrying...
[33mWARNING [0m test_integration:test_integration.py:107 Error when accessing Grafana dashboard: HTTPConnectionPool(host='grafana-0.grafana-endpoints.cos-lite.svc.cluster.local', port=3000): Max retries exceeded with url: /api/search?query=5G%20Network%20Overview (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x719b8eb7b790>: Failed to resolve 'grafana-0.grafana-endpoints.cos-lite.svc.cluster.local' ([Errno -3] Temporary failure in name resolution)")). Retrying...
[33mWARNING [0m test_integration:test_integration.py:107 Error when accessing Grafana dashboard: HTTPConnectionPool(host='grafana-0.grafana-endpoints.cos-lite.svc.cluster.local', port=3000): Max retries exceeded with url: /api/search?query=5G%20Network%20Overview (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x719b8eb7b730>: Failed to resolve 'grafana-0.grafana-endpoints.cos-lite.svc.cluster.local' ([Errno -3] Temporary failure in name resolution)")). Retrying...